### ISSUE TITLE
Save as new TestCase button does not work correctly

### ISSUE THREAD

**Issue by ehealthplatformstandards** [ehealthplatformstandards/TestServerWebApp#6]
@jmp-ehealth 
``Le bouton " add new testcase" ne marche pas pour moi. Je voudrais ajouter le 1B, fichier de St. Luc bxl.``

I still have this, also for a UZ Leuven testcase (2A1).

![2023-07-10_16h38_54](https://github.com/ehealthplatformstandards/TestServerWebApp/assets/57708154/790d87fb-9d64-4a4f-92aa-8df4c85b5030)

**Comment by bdc-ehealth** [comment]
Solved.
