### ISSUE TITLE
Problem with link between Tenant and Project for new (and existing?) users

### ISSUE THREAD

**Issue by bdc-ehealth** [ehealthplatformstandards/TestServerWebApp#8]
@jmp-ehealth 

Jan Yperman Ziekenhuis tenant and Private email tenant do not have a link to the project, although there is a project indicated:

![image](https://github.com/ehealthplatformstandards/TestServerWebApp/assets/90335317/9053e4d9-3478-445b-ba10-a623a75b0588)

Also see: https://github.com/hl7-be/lab/issues/218

**Comment by bdc-ehealth** [comment]
The problem causes the users not to see their testplan (e.g. Patricia Vandecandelaere)
![image](https://github.com/ehealthplatformstandards/TestServerWebApp/assets/90335317/46ab1f02-67a5-45f3-b643-7e36eb5895e5)

**Comment by scailliau** [comment]
Dear, 

I also have a problem with this. I've uploaded 2 testcases through Postman for the first time and for me it's also not possible to find the successful sended testcases in the 'Incoming Messages' or in 'My Test Results' on the testserver. It seems to be that the sended testresults are not connected to my tenant.

Thanks in advance.

Sharon Cailliau
AZ Delta

**Comment by jmp-ehealth** [comment]
@scailliau 
First, you had to activate the project in the dashboard (I did it for you)
Then you have access to the infos about the URL to be used in postman 
Can you retry to send a message with the correct URL and let me know

**Comment by scailliau** [comment]
Indeed, now it works. I didn't see a button to activate the project in the Dashboard. 
Thank you for your quick response!

**Comment by jmp-ehealth** [comment]
@scailliau 
You're welcome.
Goof luck for your tests ;)
Let us know if you have any other question
